# Generated by Django 5.1 on 2024-08-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_approve',
        ),
    ]
